### ISSUE TITLE
Does this work in WHMCS v7.9.x ?

### ISSUE THREAD

**Issue by kang28ivan** [markustenghamn/WHMCS-Affiliates-Anywhere#2]
Hello,
Can anyone provide experience that this modules can still work with whmcs version 7.9.x?

Thank you

**Comment by wpjohnny** [comment]
The support documentation says it does. I just bought it recently and implementing it now on my site as we speak. Just have to finalize some URLs before releasing it live.

**Comment by kang28ivan** [comment]
I already try, not working for me.

`Exception: BadFunctionCallException: mysql_result is not supported in /home/bill/public_html/includes/dbcompatfunctions.php:0 Stack trace: #0 /home/bill/public_html/modules/addons/anveto_affiliate_anywhere_plus/hooks.php(300): mysql_result(Object(PDOStatement), 0) #1 /home/bill/public_html/includes/hookfunctions.php(0): anveto_affiliate_anywhere_plus_calcAffiliateCommission(Array) #2 /home/bill/public_html/includes/functions.php(0): run_hook('CalcAffiliateCo...', Array) #3 /home/bill/public_html/affiliates.php(0): calculateAffiliateCommission(2, 1263, '0000-00-00') #4 {main}


Error: ArgumentCountError: Too few arguments to function select_query(), 2 passed in /home/bill/public_html/modules/addons/anveto_affiliate_anywhere_plus/anveto_affiliate_anywhere_plus.php on line 571 and at least 3 expected in /home/bill/public_html/includes/dbfunctions.php:0 Stack trace: #0 /home/bill/public_html/modules/addons/anveto_affiliate_anywhere_plus/anveto_affiliate_anywhere_plus.php(571): select_query('mod_anveto_affi...', 'id,domainname') #1 /home/bill/public_html/admin/addonmodules.php(0): anveto_affiliate_anywhere_plus_output(Array) #2 {main}`

**Comment by wpjohnny** [comment]
You tried it on the latest WHMCS? Did you ask their support?

**Comment by uberswe** [comment]
> I already try, not working for me.
> 
> `Exception: BadFunctionCallException: mysql_result is not supported in /home/bill/public_html/includes/dbcompatfunctions.php:0 Stack trace: #0 /home/bill/public_html/modules/addons/anveto_affiliate_anywhere_plus/hooks.php(300): mysql_result(Object(PDOStatement), 0) #1 /home/bill/public_html/includes/hookfunctions.php(0): anveto_affiliate_anywhere_plus_calcAffiliateCommission(Array) #2 /home/bill/public_html/includes/functions.php(0): run_hook('CalcAffiliateCo...', Array) #3 /home/bill/public_html/affiliates.php(0): calculateAffiliateCommission(2, 1263, '0000-00-00') #4 {main}
> 
> Error: ArgumentCountError: Too few arguments to function select_query(), 2 passed in /home/bill/public_html/modules/addons/anveto_affiliate_anywhere_plus/anveto_affiliate_anywhere_plus.php on line 571 and at least 3 expected in /home/bill/public_html/includes/dbfunctions.php:0 Stack trace: #0 /home/bill/public_html/modules/addons/anveto_affiliate_anywhere_plus/anveto_affiliate_anywhere_plus.php(571): select_query('mod_anveto_affi...', 'id,domainname') #1 /home/bill/public_html/admin/addonmodules.php(0): anveto_affiliate_anywhere_plus_output(Array) #2 {main}`

This error is caused because you use PHP 7 or higher which I recommend. If anyone wants to fix this you would need to replace the `mysql_result()` functions used in this addon with either [mysqli_result](https://www.php.net/manual/en/class.mysqli-result.php) or PDO. [WHMCS also has their own recommendations on how to interact with the database](https://developers.whmcs.com/advanced/db-interaction/) which did not exist when I initially created this addon.

I am not paying for a WHMCS license and don't have access to any of the later versions of WHMCS so I am unable to test or fix this problem.
